### ISSUE TITLE
Crash on linux wayland

### ISSUE THREAD

**Issue by qu1ck** [openscopeproject/TrguiNG#131]
Seems to happen only in flatpak or when xwayland is not available

Caused by update to tauri 1.5.4 which brought in tauri-runtime-wry 0.14.3

https://github.com/tauri-apps/tauri/issues/8515

**Comment by qu1ck** [comment]
Fixed in [v1.2.0](https://github.com/openscopeproject/TrguiNG/releases/tag/v1.2.0)

**Comment by RomanAverin** [comment]
There's still a problem with wayland
`Process 232804 (trgui-ng) of user 1000 dumped core.
                                                             Stack trace of thread 2:
                                                             #0  0x00007f6d521bae14 n/a (/usr/lib/x86_64-linux-gnu/libc.so.6 + 0x90e14)
                                                             #1  0x00007f6d52168dce n/a (/usr/lib/x86_64-linux-gnu/libc.so.6 + 0x3edce)
                                                             #2  0x00007f6d5215083f n/a (/usr/lib/x86_64-linux-gnu/libc.so.6 + 0x2683f)
                                                             #3  0x000055817720f047 n/a (/app/bin/trgui-ng + 0x2ef047)
                                                             ELF object binary architecture: AMD x86-64`

**Comment by qu1ck** [comment]
Please post full log

**Comment by RomanAverin** [comment]
```
фев 23 10:36:59 fedora-pc-local org.openscopeproject.TrguiNG.desktop[246889]: thread 'main' panicked at /run/build/TrguiNG/cargo/vendor/tauri-runtime-wry-0.14.4/src/lib.rs:2022:55:
фев 23 10:36:59 fedora-pc-local org.openscopeproject.TrguiNG.desktop[246889]: called `Result::unwrap()` on an `Err` value: Unknown { .. } - "Unknown error while interacting with the clipboard: $DISPLAY variable not set and no value was provided explicitly"
фев 23 10:36:59 fedora-pc-local org.openscopeproject.TrguiNG.desktop[246889]: note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```
