### ISSUE TITLE
Page up and page down don’t work as expected

### ISSUE THREAD

**Issue by nicknlsn** [openscopeproject/TrguiNG#72]
@jfeilbach please chime in on this one for more details.

**Comment by jfeilbach** [comment]
If I have a normal view of a row of torrents in view and there are more rows off the view pushing `PGup` or `PGdn` only works once. I am unable to push it again even though there are more pages. `PGdn` then `PGdn` again fails. Same with `PGdn` then `Pgdn` to `PGdn then `PGup` basically any multiple press fails. This occurs in window mode and full screen mode.

**Comment by qu1ck** [comment]
Fixed in [v0.9.0](https://github.com/openscopeproject/TrguiNG/releases/tag/v0.9.0)

**Comment by o010b** [comment]
Problem persists. Both as web ui and app. PgUp/PgDown works once but loses focus on the list.
